title: "Neon's now"
description: "Neon's homepage."
baseurl: ""
url: "https://neonsnow.net"

header_pages:
  - index.md
  - peter.md
  - about.md
  - contact.md

style: dark

footer: 'Nothing but true.'

# Build settings
markdown: Markdown
remote_theme: b2a3e8/jekyll-theme-console
